### ISSUE TITLE
Phoenix Plug thinks metrics aren't defined when using PlugExporter

### ISSUE THREAD

**Issue by landongn** [deadtrickster/prometheus-plugs#31]
Here's the crash dump when attempting to hit the `/metrics` route via a configured plugExporter: 

```bash

[error] #PID<0.1324.0> running AppWeb.Endpoint (cowboy_protocol) terminated
Server: app.myserver.com:80 (http)
Request: GET /metrics
** (exit) an exception was raised:
    ** (Prometheus.UnknownMetricError) Unknown metric {registry: default, name: telemetry_scrape_duration_seconds}.
        (prometheus) src/prometheus_metric.erl:142: :prometheus_metric.check_mf_exists/4
        (prometheus) src/metrics/prometheus_summary.erl:355: :prometheus_summary.insert_metric/5
        (prometheus) src/metrics/prometheus_summary.erl:161: :prometheus_summary.observe/4
        (prometheus_ex) lib/prometheus/metric/summary.ex:81: Prometheus.Metric.Summary.observe/2
        (App) lib/app/metrics/exporter.ex:2: App.Metrics.PlugExporter.scrape_data/1
        (App) lib/app/metrics/exporter.ex:2: App.Metrics.PlugExporter.call/2
        (App) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
        (App) lib/plug/debugger.ex:122: AppWeb.Endpoint."call (overridable 3)"/2
        (App) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /var/nodes/app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

This seems to crash when looking at the two `Summary` metrics present within the plug as part of reporting.  

my mix.ex: 

```
{:prometheus, "~> 4.3"},
{:prometheus_ex, "~> 3.0.5" },
{:prometheus_plugs, "~> 1.1"}
```

Not really sure what I'm doing wrong at this point.  The plug dependency looks like it's hitting an ETS table but can't find the metric, but it's not defined anywhere within my app outside of the plug dependency.  What to do?

**Comment by landongn** [comment]
to rule out the easy ones: 
- I'm calling `setup()` as defined in the docs in the `Application` start. 
- I have only one metric defined as a module (a simple gauge as a test)
- I am running the plug well after application startup, and the plug is running properly outside of any router pipelines (it's in the endpoint)
- my config is based on defaults from the plug module docs

**Comment by landongn** [comment]
Whoops.  Missed a setup() call for the plug itself.  In the applications startup, I wasn't telling the plug to `setup()` -- adding the plug module to the setup pipeline took care of the issue.
